package it.leo.rendicontationplatform.support;


public interface Constants {
    String SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG";
    String SERVICE_ALREADY_EXIST = "SERVICE_ALREADY_EXIST";
    String ACTIVITY_ALREADY_EXIST = "ACTIVITY_ALREADY_EXIST";
    String UNABLE_TO_ADD_FOR_SOMEONE_ELSE = "UNABLE_TO_ADD_FOR_SOMEONE_ELSE";
    String UNABLE_TO_EDIT_FOR_SOMEONE_ELSE = "UNABLE_TO_EDIT_FOR_SOMEONE_ELSE";
    String UNABLE_TO_DELETE_FOR_SOMEONE_ELSE = "UNABLE_TO_DELETE_FOR_SOMEONE_ELSE";


}
